spring:
  application:
    name: weather-api
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

server:
  port: ${SERVER_PORT:8080}

weather-api:
  baseURL: ${WEATHER_API_BASE_URL:https://weather.visualcrossing.com/VisualCrossingWebServices/rest/services/timeline/}
  apiKey: ${WEATHER_API_KEY:}
  cacheTtlSeconds: ${WEATHER_CACHE_TTL_SECONDS:5}
  rateLimit: ${WEATHER_RATE_LIMIT:10}